news_base/urls.py
#!/usr/bin/env python3
# -*- coding:utf-8 -*-


from . import views

from django.urls import path





app_name = 'news_base'

urlpatterns = [
    #
    # path('', views.index, name='index'),
    path('news/', views.news, name='news'),
    # 交易列表
    path('events/', views.events, name='events'),
    # 信息提交
    path('imformation/', views.imformation, name='imformations'),
    # 公司介绍
    path('about/', views.about, name='about'),
    # 欢迎合作
    path('', views.cooperation, name='cooperation'),

    # 服务范围
    path('services/', views.services, name='services')


    # 招聘信息
]

shangchensite/urls.py
from django.contrib import admin
from django.urls import path, include


from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [

    path('admin/', admin.site.urls),

    path('', include('news_base.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

news_base/models.py
from django.db import models
from django.utils.timezone import now

# Create your models here.

# 新闻
class News(models.Model):
    title = models.CharField('标题', max_length=100, blank=True, default='')
    image = models.ImageField('图片', upload_to="media/newspictures", blank=True)
    date = models.DateTimeField('日期', auto_now_add=True)
    create_time = models.DateField('创建日期', default=now)
    body = models.TextField('正文')


    def __str__(self):
        return self.title

    class Meta:
        ordering = ['-create_time']
        verbose_name = '新闻'
        verbose_name_plural = verbose_name


#交易记录
class Events(models.Model):
    title = models.CharField('标题', max_length=100, default='')
    image = models.ImageField('上传交易记录', upload_to='media/evetsimages', blank=True)
    create_time = models.DateTimeField('上传时间', auto_now_add=True)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['-create_time']
        verbose_name = '交易记录'
        verbose_name_plural = verbose_name


# 联系方式

class Imformation(models.Model):
    name = models.CharField('姓名', max_length=68, default='如张三')
    tel  = models.CharField('电话', max_length=100, default='', )
    sub = models.TextField('留言', default='如：求职/办理业务', blank=True, null=True)
    create_time = models.DateField('时间', default=now)


    def __str__(self):
        return self.name

    class Meta:
        ordering = ('-create_time',)
        verbose_name = '留言信息'
        verbose_name_plural = verbose_name


class About(models.Model):
    title = models.CharField('简要介绍', max_length=128)
    text = models.TextField('详细介绍')
    img = models.ImageField('配图', upload_to='media/about')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = '尚辰保理介绍'
        verbose_name_plural = verbose_name

# 欢迎合作
class  Cooperation(models.Model):
    text = models.TextField('欢迎合作')
    date = models.DateField('填写日期', auto_now_add=now)

    def __str__(self):
        return self.text

    class Meta:
        verbose_name = '合作邀请文案'
        verbose_name_plural = verbose_name


class Services(models.Model):
    title = models.CharField('业务名称', max_length=128)
    text = models.TextField('服务详细')
    img = models.ImageField('配图', upload_to='media/services')
    creat = models.DateTimeField('编写日期', auto_now_add=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = '服务内容'
        verbose_name_plural = '服务内容'
        ordering = ('-creat',)

news_base/forms.py
#!/usr/bin/env python3
# -*- coding:utf-8 -*-

from django import forms


class ImformationForm(forms.Form):
    name = forms.CharField(label='姓名', max_length=128, required=False)
    tel = forms.CharField(label='电话', max_length=128, required=False)
    sub = forms.CharField(label='其他', max_length=50, )

news_base/views.py
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from . import models

from . import forms

# Create your views here.

def news(request):
    news_list = models.News.objects.all().order_by('-date')[:6]
    paginator = Paginator(news_list, 6)

    page = request.GET.get('page')

    try:
        news = paginator.page(page)
    except PageNotAnInteger:
        news = paginator.page(1)
    except EmptyPage:
        news = paginator.page(paginator.num_pages)

    return render(request, 'news_base/news.html', {'news_list': news_list})



def new_detail(request, pk):
    new = get_object_or_404(models.News, pk=id)
    etx = {
        "title": models.News.title,
        'date': models.News.create_time,
        'image': models.News.image,
        'body': models.News.body
    }
    return render(request, 'news_base/news.html', etx)





def events(request):
    """
    交易记录列表

    """
    events_list = models.Events.objects.all().order_by('-create_time')[:9]
    papginator = Paginator(events_list, 9)
    page = request.GET.get('page')

    try:
        events = papginator.page(page)
    except PageNotAnInteger:
        events = papginator.page(1)
    except EmptyPage:
        events = papginator.page(papginator.num_pages)

    return render(request, 'news_base/events.html', {'events_list': events_list})

def event_detail(request, pk):
    """交易记录详情"""
    event = get_object_or_404(models.Events, pk=id)
    etx = {
        'title': models.Events.title,
        'image': models.Events.image
    }
    return render(request, 'news_base/events.html', etx)





def imformation(request):
    imformation_form = forms.ImformationForm()

    if request.method == "POST":
        imformation_form = forms.ImformationForm(request.POST)
        if imformation_form.is_valid():
            b = models.Imformation()
            b.name = imformation_form.cleaned_data['name']
            b.sub = imformation_form.cleaned_data['sub']
            b.tel = imformation_form.cleaned_data['tel']
            b.save()

        else:
            message = '请检查填写内容'
        return render(request, 'news_base/imformation.html', locals())
    return render(request, 'news_base/imformation.html', locals())



def about(request):
    about_list = models.About.objects.all().order_by('-pk')[:1]

    papginator = Paginator(about_list, 1)
    page = request.GET.get('page')

    try:
        about = papginator.page(page)
    except PageNotAnInteger:
        about = papginator.page(1)
    except EmptyPage:
        about = papginator.page(papginator.num_pages)

    return render(request, 'news_base/about.html', {'about_list': about_list})

def index(request):
    return render(request, 'news_base/index.html')


def cooperation(request):

    cooperation = models.Cooperation.objects.all().order_by('-pk')[:1]

    papginator = Paginator(cooperation, 1)

    page = request.GET.get('page')

    try:
        about = papginator.page(page)
    except PageNotAnInteger:
        about = papginator.page(1)
    except EmptyPage:
        about = papginator.page(papginator.num_pages)

    return render(request, 'news_base/index.html', {'cooperation': cooperation})


def services(request):
    services_list = models.Services.objects.all()[:6]
    return render(request, 'news_base/services.html', {'services': services_list})

news_base/templates/base.html
{% load staticfiles %}

<!DOCTYPE HTML>
<html lang="zh-CN">
<head>
    <title>{% block title %}base{% endblock %}</title>
    <link href="{% static 'news_base/css/bootstrap.css' %}" rel="stylesheet" type="text/css" media="all">
    <link href="{% static 'news_base/css/style.css' %}" rel="stylesheet" type="text/css" media="all" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="keywords" content="Hiking Responsive web template, Bootstrap Web Templates, Flat Web Templates, Andriod Compatible web template,
Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyErricsson, Motorola web design" />
    <script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,600,300,700,800' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="css/flexslider.css" type="text/css" media="screen" />
    <script src="{% static 'news_base/js/jquery.min.js' %}"></script>
    <link href="{% static 'news_base/css/popuo-box.css' %}" rel="stylesheet" type="text/css" media="all"/>
    <script src="{% static 'news_base/js/jquery.magnific-popup.js' %}" type="text/javascript"></script>
    <script>
		$(document).ready(function() {
		$('.popup-with-zoom-anim').magnificPopup({
		type: 'inline',
		fixedContentPos: false,
		fixedBgPos: true,
		overflowY: 'auto',
		closeBtnInside: true,
		preloader: false,
		midClick: true,
		removalDelay: 300,
		mainClass: 'my-mfp-zoom-in'
		});
		});
	</script>
{% block css %}{% endblock %}
</head>

<body>
<!-- header -->
			<div class="header-bottom">
				<div class="container">
					<div class="logo">
						<a href="news_base/index.html"><img src="images/logo.png" class="img-responsive" alt="" /></a>
					</div>
					<div class="head-nav">
						<span class="menu"> </span>
							<ul>
								<li class="active"><a href="{% url 'news_base:cooperation' %}">首页</a></li>
								<li><a href="{% url 'news_base:about' %}">公司介绍</a></li>
								<li><a href="{% url 'news_base:news' %}">新闻动态</a></li>
								<li><a href="{% url 'news_base:events' %}">成交记录</a></li>
								<li><a href="{% url 'news_base:services' %}">业务范围</a></li>
								<li><a href="{% url 'news_base:imformations' %}">联系我们</a></li>

								<div class="clearfix"> </div>
						</ul>
					</div>
						<div class="clearfix"> </div>
						<!-- script-for-nav -->
					<script>
						$( "span.menu" ).click(function() {
						  $( ".head-nav ul" ).slideToggle(300, function() {
							// Animation complete.
						  });
						});
					</script>
				<!-- script-for-nav -->
				</div>

			</div>

{% block content %}  {% endblock %}

<!-- footer -->
	<div class="footer">
		<div class="container">
		<div class="col-md-3 information">
				<h4>信息</h4>
				<div class="nav-bottom">
						<ul>
							<li><a href="{% url 'news_base:about' %}">公司介绍</a></li>
							<li><a href="{% url 'news_base:news' %}">新闻动态</a></li>
							<li><a href="{% url 'news_base:events' %}">成交记录</a></li>
							<li><a href="{% url 'news_base:services' %}">业务范围</a></li>
							<li><a href="{% url 'news_base:imformations' %}">联系我们</a></li>

								<div class="clearfix"></div>
						</ul>
					</div>
			</div>
			<div class="col-md-3 keep">
				<h4>关注我们</h4>
				<div class="social">
						<ul>
							<li><a href="#"><i class="facebok"> </i></a></li>
							<li><a href="#"><i class="twiter"> </i></a></li>
							<li><a href="#"><i class="rss"> </i></a></li>
								<div class="clearfix"></div>
						</ul>
					</div>
			</div>
			<div class="col-md-3 email">
				<h4>邮箱 </h4>
				<p>深圳尚辰商业保理有限公司</p>
				<div class="email-top">
						<form>
							<input type="text" class="text" value="Email" onfocus="this.value = '710567585@qq.com';" onblur="if (this.value == '') {this.value = 'Email';}">
						</form>
				</div>
			</div>
			<div class="col-md-3 conta">
				<h4>联系电话</h4>
				<p>母先生: 185 8399 9704</p>
				<p>任女士: 132 8108 5871</p>
			</div>
				<div class="clearfix"> </div>
			<div class="bottom">
				<p>Copyright &copy; 2015.Company name All rights reserved.More Templates <a href="http://www.cssmoban.com/" target="_blank" title="模板之家">模板之家</a> - Collect from <a href="http://www.cssmoban.com/" title="网页模板" target="_blank">网页模板</a></p>
			</div>
		</div>
	</div>
<!-- footer -->


</body>
</html>

news_base/templates/news_base/about.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}公司介绍{% endblock %}
{% block content %}

<div class="banner1">
		<div class="container">
	</div>
	</div>
<!-- header -->
<!-- about -->
	<div class="main">
		<div class="container">
			<div class="about">
				<h4>关于我们</h4>
			<div class="about-bottom">
                {% for about in about_list %}
				<div class="col-md-8 about-grid">
					<h6><a>{{ about.title }}</a></h6>
					<p>{{ about.text }}</p>
				</div>
				<div class="col-md-4">
				<div class="view effect">
					<img src="{{ MEDIA_URL }}{{ about.img }}" alt="image" class="img-responsive zoom-img">
				</div>
				</div>
				<div class="clearfix"> </div>
                    {% endfor %}
                    </div>

		</div>
	</div>
	</div>
<!-- about -->

{% endblock %}

news_base/templates/news_base/business.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>业务范围</title>
</head>
<body>

</body>
</html>

news_base/templates/news_base/events.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}交易记录{% endblock %}
{% block content %}
	<div class="banner1">
		<div class="container">

	</div>
	</div>
<!-- header -->


<!-- about -->
	<div class="main">
		<div class="container">
		<h2>交易记录</h2>
		<!-- portfolio-section -->
	 <div class="portfolio"  id="portfolio">
	 <div class="welcome-top">
				<div id="portfoliolist">
                    {% for event in events_list %}
					<div class="portfolio card mix_all  wow bounceIn" data-wow-delay="0.4s" data-cat="card" style="display: inline-block; opacity: 1;">
						<div class="portfolio-wrapper grid_box">
							<div class="welcome-1">
								<a href="{{ MEDIA_URL }}{{ event.image }}"  class="swipebox"  title="{{ event.title }}"> <img src="{{ MEDIA_URL }}{{ event.image }}" width="350" height="234" class="img-responsive" alt=""><span class="zoom-icon"></span> </a>
							</div>
						</div>
		            </div>
                    {% endfor %}
					<div class="clearfix"></div>

					<div class="clearfix"></div>
    </div>
	</div>
	  <!-- Script for gallery Here -->
				<script type="text/javascript" src="{% static 'news_base/js/jquery.min.js' %}"></script>
					<script type="text/javascript">
					$(function () {

						var filterList = {

							init: function () {

								// MixItUp plugin
								// http://mixitup.io
								$('#portfoliolist').mixitup({
									targetSelector: '.portfolio',
									filterSelector: '.filter',
									effects: ['fade'],
									easing: 'snap',
									// call the hover effect
									onMixEnd: filterList.hoverEffect()
								});

							},

							hoverEffect: function () {

								// Simple parallax effect
								$('#portfoliolist .portfolio').hover(
									function () {
										$(this).find('.label').stop().animate({bottom: 0}, 200, 'easeOutQuad');
										$(this).find('img').stop().animate({top: -30}, 500, 'easeOutQuad');
									},
									function () {
										$(this).find('.label').stop().animate({bottom: -40}, 200, 'easeInQuad');
										$(this).find('img').stop().animate({top: 0}, 300, 'easeOutQuad');
									}
								);

							}

						};

						// Run the show!
						filterList.init();


					});
					</script>
<!-- portfolio-section  -->

		</div>
	</div>
</div>
<!-- about -->
{% endblock %}

news_base/templates/news_base/imformation.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block title %}联系我们{% endblock %}

{% block content %}
    	<div class="banner1">
		<div class="container">
	</div>
	</div>
<!-- header -->

<!-- contact -->
<div class="contact-data">
			<div class="container">
		       <h2>取得联系</h2>
		          <div class="contact-form">
					     <form method="post" action="" class="left_form">
					    {{ imformation_form }}
                             {% csrf_token %}

                             <span><input type="submit"  class="myButton"></span>
					    </form>
					    <div class="clear"></div>
				  </div>
				  <div class="content_bottom">
				 	<div class="company_address">
				     	<h2>位置</h2>
						    	<p>深圳市龙岗区坂田街道,</p>
						   		<p>月朗苑3栋2单元2B室,</p>
						   		<p>中国·广东</p>
				   		<p>电话:185 8399 9704</p>
				 	 	<p>Email: <span><a href="mailto:517981402@qq.com">517981402(at)qq.com</a></span></p>

				     </div>
				       <div class="contact_info">
    	 				<h2>我们在这里</h2>
					    	  <div class="map">

							   	    <iframe frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.co.in/maps?f=q&amp;source=s_q&amp;hl=en&amp;geocode=&amp;q=Lighthouse+Point,+FL,+United+States&amp;aq=4&amp;oq=light&amp;sll=26.275636,-80.087265&amp;sspn=0.04941,0.104628&amp;ie=UTF8&amp;hq=&amp;hnear=Lighthouse+Point,+Broward,+Florida,+United+States&amp;t=m&amp;z=14&amp;ll=26.275636,-80.087265&amp;output=embed"></iframe><br><small><a href="https://maps.google.co.in/maps?f=q&amp;source=embed&amp;hl=en&amp;geocode=&amp;q=Lighthouse+Point,+FL,+United+States&amp;aq=4&amp;oq=light&amp;sll=26.275636,-80.087265&amp;sspn=0.04941,0.104628&amp;ie=UTF8&amp;hq=&amp;hnear=Lighthouse+Point,+Broward,+Florida,+United+States&amp;t=m&amp;z=14&amp;ll=26.275636,-80.087265" style="color:#999;text-align:left;font-size:13px">地图</a></small>
							  </div>
      				     </div>
				      <div class="clearfix"></div>
	                </div>
		 	  </div>
			</div>
  <!-- contact -->
{% endblock %}

news_base/templates/news_base/index.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block title%}首页{% endblock %}


{% block content %}
    <!--轮播图-->
    <div class="banner">
		<div class="container">
		<div class="wmuSlider example1 section" id="section-1">
			   <article style="position: absolute; width: 100%; opacity: 0;">
			   	   	<div class="banner-info">
						<h1>深圳尚辰商业保理有限公司 </h1>
						<p>rjj</p>
					</div>
				</article>
		  </div>
		<!-- script -->
          <script src="{% static 'news_base/js/jquery.wmuSlider.js' %}"></script>
			<script>
       			$('.example1').wmuSlider();
   		    </script>
			<!-- script -->
	</div>
	</div>
<!-- header -->

    <!-- curabitur -->
	<div class="curabitur">
		<div class="container">
			<div class="col-md-4 curabitur-top">
				<i class="hammer"></i>
				<h4>Contrary to popular</h4>
				<p>Pellentesque eu congue sapien. Donec hendrerit viverra finibus. Nulla eget sollicitudin leo. Morbi lacinia libero urna necrfaucibus nulla mollis et. </p>
				<a href="#" class="btn  btn-1c btn1 btn-1d">More</a>
			</div>
			<div class="col-md-4 curabitur-top">
				<i class="timer"></i>
				<h4>Contrary to popular</h4>
				<p>Pellentesque eu congue sapien. Donec hendrerit viverra finibus. Nulla eget sollicitudin leo. Morbi lacinia libero urna necrfaucibus nulla mollis et. </p>
				<a href="#" class="btn  btn-1c btn1 btn-1d">More</a>
			</div>
			<div class="col-md-4 curabitur-top">
				<i class="tent"></i>
				<h4>Contrary to popular</h4>
				<p>Pellentesque eu congue sapien. Donec hendrerit viverra finibus. Nulla eget sollicitudin leo. Morbi lacinia libero urna necrfaucibus nulla mollis et. </p>
				<a href="#" class="btn  btn-1c btn1 btn-1d">More</a>
			</div>
			<div class="clearfix"> </div>
		</div>
	</div>

<!-- curabitur -->

<!-- welcome -->
	<div class="welcome">
		<div class="container">
			<h2>欢迎合作</h2>

            {% for cxd in  cooperation %}
			<p>{{ cxd.text }}</p>
            {% endfor %}


		</div>
	</div>
<!-- welcome -->
{% endblock %}

news_base/templates/news_base/news.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block title %}新闻动态{% endblock %}

{% block content %}

<!-- header -->
	<div class="banner1">
		<div class="container">
	</div>
	</div>
<!-- header -->


<!-- about -->
	<div class="main">
		<div class="container">
		<!-- news -->
		<div class="news">
			<h3>近期新闻</h3>

				<div class="news-grids">
                    {% for new in  news_list %}
					<div class="col-md-4 news-grid">
						<div class="news-grid-text">
							<h4>{{ new.title }}</h4>
							<span>{{ new.date }}</span>
						</div>
						<img src="{{ MEDIA_URL }}{{ new.image }} " width="350" height="234" class="img-responsive" alt="" />
						<p>{{ new.body }}</p>
					</div>
                        {% endfor %}
			</div>
		</div>
		<!-- //news -->
		</div>
	</div>
{% endblock %}

news_base/templates/news_base/services.html
{% extends 'base.html' %}
{% block title %}服务范围{% endblock %}
{% load staticfiles %}


{% block content  %}
<!--services start here-->
<div class="services">
	<div class="container">
		<div class="services-main">
				<h3>我们的服务</h3>
			<div class="services-bot">
                {% for service in services %}
				<div class="col-md-6 services-grid">
					<div class="col-md-5 serv-img">
						<a><img src="{{ MEDIA_URL }}{{ service.img }}" alt="" class="img-responsive"></a>
					</div>
					<div class="col-md-7 serv-text">
						<h4><a>{{ service.title }}</a></h4>
						<p>{{ service.text }}</p>
					</div>
				  <div class="clearfix"> </div>
				</div>
                {% endfor %}

			   <div class="clearfix"> </div>

			</div>

		</div>
	</div>
</div>

{% endblock  %}